### ISSUE TITLE
Version 2.8.1: problem in separate 

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/editrules#3]
```
E <- editset(expression(
    married %in% c(TRUE,FALSE),
    if (married==TRUE) age >=17
  ))

  le <- localizeErrors(E, data.frame(married=TRUE, age=9))
  expect_equal(sum(le$adapt), 1, info="bb returns correct result")  
```

currently fails due to `separate(E)` in `localizeErrors`

**Comment by ArcherWoo** [comment]
I have separate issue as well. I use both editrules and dplyr package. I found that when run editrules package, the separate function in dplyr was gone.

**Comment by markvanderloo** [comment]
That is because both editrules and dplyr define a function with the name `separate`. Use `editrules::separate` to make sure you get the right one.

But please also have a look at our `validate` package. It replaces editrules and is in general more convenient.

**Comment by edwindj** [comment]
In addition, this is not a bug, but a property of R when loading packages. When R packages are loaded with functions that have identical names, R by default uses that last one (it masks the other first one). The first one is still available using <packagename>::<functionname>

So in your case you may want to load `editrules` first and then `tidyr`, so `separate` will point to `tidyr::separate`. (Please note that the function `separate` of `editrules` was created long before `tidyr` came into existence).

But as Mark said: `validate` and `errorlocate` are the successors of `editrules`.
